version: 0.0
os: linux
files:
  - source: /ACC_Backup/
    destination: /var/www/html/

permissions:
  - object: /var/www/html/
    pattern: "*"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: /ACC_Backup/scripts/before_install.sh
      timeout: 1000
      runas: root
  
  AfterInstall:
    - location: /ACC_Backup/scripts/after_install.sh
      timeout: 1500
      runas: root

  ApplicationStart:
    - location: /ACC_Backup/scripts/app_start.sh
      timeout: 301
      runas: root