version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/ACC_Backup

permissions:
  - object: /home/ubuntu/ACC_Backup
    pattern: "*"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 1000
      runas: root
  
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 1500
      runas: root

  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 301
      runas: root