FROM node:22

# Dockerfile
ARG APS_CLIENT_ID
ARG APS_CLIENT_SECRET
ARG APS_CALLBACK_URL
ARG SERVER_SESSION_SECRET

ENV APS_CLIENT_ID=${APS_CLIENT_ID}
ENV APS_CLIENT_SECRET=${APS_CLIENT_SECRET}
ENV APS_CALLBACK_URL=${APS_CALLBACK_URL}
ENV SERVER_SESSION_SECRET=${SERVER_SESSION_SECRET}

WORKDIR /ACC_BACKUP

COPY package*.json ./

RUN npm install

COPY . .

RUN mkdir -p ./tmp

EXPOSE 8080

CMD [ "node", "server.js" ]