version: '3.8'

services:
  app:
    image: 339713031143.dkr.ecr.ap-south-1.amazonaws.com/acc_backup:latest
    container_name: acc_backup
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - APS_CLIENT_ID=${APS_CLIENT_ID}
      - APS_CLIENT_SECRET=${APS_CLIENT_SECRET}
      - APS_CALLBACK_URL=${APS_CALLBACK_URL}
      - SERVER_SESSION_SECRET=${SERVER_SESSION_SECRET}
    restart: always
